---
title: "Code Reference"
author: "Josephine Wright"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Rules:**
+ `filter(condition1, condition2)` will return rows where both conditions are met. By default the ,   means &.    
+ `filter(condition1, !condition2)` will return all rows where condition one is true but condition   2 is not.  
+ `filter(condition1 | condition2)` will return rows where condition 1 or condition 2 is met. 

**Graphs:**
bar: `geom_bar()`
box: `geom_boxplot()`
dot plot: `geom_point()`
  + line of best fit: `geom_smooth(method=lm)`
  + standard error: `geom_smooth(method=lm, se=T)`
  + scale_y_log10()+
  + scale_x_log10()+
bar(x&y): `geom_col()`

**Cleaning Data:**

`clean_names` converts all column names to typical R conventions(6_1)
  + does not change data itself
`mutate(across(c(data_columns), tolower))` will change specific data to lowercase(6_1)
`mutate(across(where(is.character), tolower))` will change all to lowercase without changing all data to chr(6_1)
`mutate(across(c(data_columns), as.factor))` will change specific data to factors(hw6)

**Misc Commands:**

`distinct()` looks for all unique observations in rows.(6_1)
  distinct(): across all rows
  distinct(data_column): distinct data in column
  distinct(data_column, data_column, .keep_all=T): will allow to see all of data on each distinct    data of first column
  
`mutate()` creates new columns from existing columns in a data frame.(6_1)

`mutate()` & `across()` apply a function to multiple columns.(6_1)
  mutate(across(ends_with("mm"), ~./10))
      `~` indicates that what follows is a formula (lambda function).
      `.` represents the current column being processed 
      `./10` means "take the current column and divide it by 10". This operation is applied to           all columns that end with `mm`.
      
`if.else()` allows use of `mutate()` but doesn't mess with the whole column, usually for converting -999 to NA (6_1)

`relocate()` allows you to move columns to different locations within a data frame(5_1)

`select()`(5_1)

`filter()` to extract data that meets a certain criteria within a row(5_2)
  + can use operators > < == and !
  + `%in%` determines whether or not a value is part of a vector
  + `near` extracts data close to a certain value, but must specify tolerance (split evenly above    and below value)
  
  **Colors/Aesthetics**
  lab 10 - aesthetics with plots
  lab 11 - colors & density plots
  
  **NAs**
  `summarise(across(everything(), ~sum(is.na(.))))` to count NAs in each column
  `summarise(across(everything(), ~sum(.==-999)))` to count -999s in each column
  
  `life_history_no_nas <- read_csv("data/mammal_lifehistories_v3.csv", na="-999") %>% 
  clean_names()` example of how to read in data and convert -999 to NA's
  
  `miss_var_summary` provides a summary of NA's across the data frame
  `gg_miss_var` to visualize the number of NA's in each variable
  
  `replace_with_na_all(condition=~.x %in% c(common_na_numbers, common_na_strings))`
  
  
  **Shiny**
  lab 14_2
  
  **Maps**
  lab 14_1
  
  
  
  
  
  
        



